### ISSUE TITLE
Missing files in 0.0.37 release

### ISSUE THREAD

**Issue by lig** [samuelcolvin/foxglove#32]
In foxglove-web 0.0.36 there were `testing.py` and `test_server.py` files in the package distribution. In foxglove-web 0.0.37 those files are missing.

This affects `hooky` testing suite as it uses `TestClient` and `DummyServer`.

It's worth mentioning that files are present in `tar.gz` distribution but still won't be installed from it.

**Comment by samuelcolvin** [comment]
Okay, let's fix and make a new release.
